### PR TITLE
Moved api and error documentation onto a separate folder and removed it from readme

### PR DESCRIPTION
**Pull request by dafortune**

### CODE REVIEW

**Comment by hzalaz** [comment]
Looks good, I'd rework the configuration section  a bit:

```
var auth0GuardianJS = require('auth0-guardian-js')({
    serviceUrl: "https://{TENANT_NAME}.guardian.auth0.com",
    requestToken: "{REQUEST_TOKEN}",

    issuer: {
        label: "{FRIENDLY_TENANT_NAME}",
        name: "{TENANT_NAME}",
    }
});
```

#### serviceUrl

Guardian API baseUrl for your Auth0 account that is formed by your account name (or tenant) with the following suffixes depending the region your Auth0 account is from:

- US: https://{name}.guardian.auth0.com
- AU: https://{name}.au.guardian.auth0.com
- EU: https://{name}.eu.guardian.auth0.com

So if your account domain is `samples.eu.auth0.com`, your guardian serviceUrl will be `samples.eu.guardian.auth0.com`

#### requestToken

`How to get it and what is used for`

#### issuer

`What each attribute means and how to get them`

**Comment by hzalaz** [comment]
And please add the following footer

```
## Issue Reporting

If you have found a bug or if you have a feature request, please report them at this repository issues section. Please do not report security vulnerabilities on the public GitHub issue tracker. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

## Author

[Auth0](auth0.com)

## License

This project is licensed under the MIT license. See the [LICENSE](LICENSE) file for more info.
```

**Comment by fiddur** [comment]
> var auth0GuardianJS = require('auth0-guardian-js')({

That wouldn't give you access to the form post helper that is directly on the module.

**Comment by fiddur** [comment]
Hmm, I see now that formPostHelper is only on the examples, but since the require is directly instantiated, the recent 'bug fix' makes the example wrong...

**Pull request closed without merging**
